---
- hosts: localhost
  become: yes

  vars_files:
    - ./vars/credentials.yml

  tasks:

    - name: generate SSH keys
      user:
        name: "{{ default['user'] }}"
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa

    - name: copy SSH key to node
      command: >
        sshpass -p "{{ default['password'] }}"
        ssh-copy-id -i /home/"{{ default['user'] }}"/.ssh/id_rsa.pub
        -o StrictHostKeyChecking=no "{{ default['user'] }}"@{{ item }}
      with_items:
        - 192.168.10.2
        - 192.168.10.3
...
